import Head from 'next/head';

const Home = () => {
  const array = new Array(100).fill(10);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {array.map((_, i) => (
        <div key={i}>This is page2</div>
      ))}
    </>
  );
};

export default Home;